
#from PyQt5 import QtCore, QtWidgets, QtGui
#from PyQt5.QtWidgets import *
#from Mutilthread import*
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtGui import QDoubleValidator
QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\HUAWEI\Desktop\concrete1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(680, 520)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelmain = QtWidgets.QLabel(self.centralwidget)
        self.labelmain.setGeometry(QtCore.QRect(9, 9, 617, 30))
        self.labelmain.setMinimumSize(QtCore.QSize(600, 0))
        self.labelmain.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelmain.setFont(font)
        self.labelmain.setStyleSheet("font: 20pt \"宋体\";")
        self.labelmain.setObjectName("labelmain")
        self.labelinput = QtWidgets.QLabel(self.centralwidget)
        self.labelinput.setGeometry(QtCore.QRect(9, 43, 360, 25))
        self.labelinput.setMinimumSize(QtCore.QSize(360, 25))
        self.labelinput.setMaximumSize(QtCore.QSize(354, 25))
        self.labelinput.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"font: 11pt \"宋体\";")
        self.labelinput.setLineWidth(2)
        self.labelinput.setObjectName("labelinput")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setEnabled(True)
        self.image.setGeometry(QtCore.QRect(9, 72, 341, 181))
        self.image.setMinimumSize(QtCore.QSize(280, 181))
        self.image.setMaximumSize(QtCore.QSize(341, 181))
        self.image.setStyleSheet("image:url(./data\\\show.png)")
        self.image.setObjectName("image")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 277, 158, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lable_b = QtWidgets.QLabel(self.layoutWidget)
        self.lable_b.setMinimumSize(QtCore.QSize(70, 0))
        self.lable_b.setObjectName("lable_b")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lable_b)
        self.b = QtWidgets.QLineEdit(self.layoutWidget)
        self.b.setMinimumSize(QtCore.QSize(0, 22))
        self.b.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.b.setClearButtonEnabled(True)
        self.b.setObjectName("b")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.b)
        self.label_h = QtWidgets.QLabel(self.layoutWidget)
        self.label_h.setMinimumSize(QtCore.QSize(70, 0))
        self.label_h.setObjectName("label_h")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_h)
        self.h = QtWidgets.QLineEdit(self.layoutWidget)
        self.h.setMinimumSize(QtCore.QSize(0, 22))
        self.h.setClearButtonEnabled(True)
        self.h.setObjectName("h")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.h)
        self.label_L = QtWidgets.QLabel(self.layoutWidget)
        self.label_L.setMinimumSize(QtCore.QSize(70, 0))
        self.label_L.setObjectName("label_L")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_L)
        self.l = QtWidgets.QLineEdit(self.layoutWidget)
        self.l.setMinimumSize(QtCore.QSize(0, 22))
        self.l.setClearButtonEnabled(True)
        self.l.setObjectName("l")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.l)
        self.label_as = QtWidgets.QLabel(self.layoutWidget)
        self.label_as.setMinimumSize(QtCore.QSize(70, 0))
        self.label_as.setObjectName("label_as")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_as)
        self.a_s = QtWidgets.QLineEdit(self.layoutWidget)
        self.a_s.setMinimumSize(QtCore.QSize(0, 22))
        self.a_s.setClearButtonEnabled(True)
        self.a_s.setObjectName("a_s")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.a_s)
        self.label_N = QtWidgets.QLabel(self.layoutWidget)
        self.label_N.setMinimumSize(QtCore.QSize(70, 0))
        self.label_N.setObjectName("label_N")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_N)
        self.N = QtWidgets.QLineEdit(self.layoutWidget)
        self.N.setMinimumSize(QtCore.QSize(0, 22))
        self.N.setClearButtonEnabled(True)
        self.N.setObjectName("N")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.N)
        self.label_M1 = QtWidgets.QLabel(self.layoutWidget)
        self.label_M1.setMinimumSize(QtCore.QSize(70, 0))
        self.label_M1.setObjectName("label_M1")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_M1)
        self.M1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.M1.setMinimumSize(QtCore.QSize(0, 22))
        self.M1.setClearButtonEnabled(True)
        self.M1.setObjectName("M1")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.M1)
        self.label_M2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_M2.setMinimumSize(QtCore.QSize(70, 0))
        self.label_M2.setObjectName("label_M2")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_M2)
        self.M2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.M2.setMinimumSize(QtCore.QSize(80, 22))
        self.M2.setClearButtonEnabled(True)
        self.M2.setObjectName("M2")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.M2)
        self.labelbasenum = QtWidgets.QLabel(self.centralwidget)
        self.labelbasenum.setGeometry(QtCore.QRect(9, 257, 151, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelbasenum.sizePolicy().hasHeightForWidth())
        self.labelbasenum.setSizePolicy(sizePolicy)
        self.labelbasenum.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.labelbasenum.setObjectName("labelbasenum")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(180, 413, 173, 48))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setHorizontalSpacing(1)
        self.formLayout_3.setObjectName("formLayout_3")
        self.labelconcrete = QtWidgets.QLabel(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelconcrete.sizePolicy().hasHeightForWidth())
        self.labelconcrete.setSizePolicy(sizePolicy)
        self.labelconcrete.setMinimumSize(QtCore.QSize(90, 20))
        self.labelconcrete.setObjectName("labelconcrete")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelconcrete)
        self.labelsteel = QtWidgets.QLabel(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelsteel.sizePolicy().hasHeightForWidth())
        self.labelsteel.setSizePolicy(sizePolicy)
        self.labelsteel.setMinimumSize(QtCore.QSize(90, 20))
        self.labelsteel.setObjectName("labelsteel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelsteel)
        self.ctype = QtWidgets.QComboBox(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctype.sizePolicy().hasHeightForWidth())
        self.ctype.setSizePolicy(sizePolicy)
        self.ctype.setMinimumSize(QtCore.QSize(80, 0))
        self.ctype.setMaximumSize(QtCore.QSize(110, 16777215))
        self.ctype.setObjectName("ctype")
        self.ctype.addItem("")
        self.ctype.addItem("")
        self.ctype.addItem("")
        self.ctype.addItem("")
        self.ctype.addItem("")
        self.ctype.addItem("")
        self.ctype.addItem("")
        self.ctype.addItem("")
        self.ctype.addItem("")
        self.ctype.addItem("")
        self.ctype.addItem("")
        self.ctype.addItem("")
        self.ctype.addItem("")
        self.ctype.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ctype)
        self.rtype = QtWidgets.QComboBox(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rtype.sizePolicy().hasHeightForWidth())
        self.rtype.setSizePolicy(sizePolicy)
        self.rtype.setMinimumSize(QtCore.QSize(80, 20))
        self.rtype.setMaximumSize(QtCore.QSize(110, 16777215))
        self.rtype.setObjectName("rtype")
        self.rtype.addItem("")
        self.rtype.addItem("")
        self.rtype.addItem("")
        self.rtype.addItem("")
        self.rtype.addItem("")
        self.rtype.addItem("")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.rtype)
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(180, 334, 191, 75))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setHorizontalSpacing(0)
        self.formLayout_2.setVerticalSpacing(2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.labelfc = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelfc.sizePolicy().hasHeightForWidth())
        self.labelfc.setSizePolicy(sizePolicy)
        self.labelfc.setMinimumSize(QtCore.QSize(90, 20))
        self.labelfc.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelfc.setObjectName("labelfc")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelfc)
        self.fc = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fc.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fc.sizePolicy().hasHeightForWidth())
        self.fc.setSizePolicy(sizePolicy)
        self.fc.setMinimumSize(QtCore.QSize(80, 0))
        self.fc.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fc.setClearButtonEnabled(True)
        self.fc.setObjectName("fc")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fc)
        self.labelfy = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelfy.sizePolicy().hasHeightForWidth())
        self.labelfy.setSizePolicy(sizePolicy)
        self.labelfy.setMinimumSize(QtCore.QSize(90, 20))
        self.labelfy.setObjectName("labelfy")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelfy)
        self.fy = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fy.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fy.sizePolicy().hasHeightForWidth())
        self.fy.setSizePolicy(sizePolicy)
        self.fy.setMinimumSize(QtCore.QSize(80, 0))
        self.fy.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fy.setClearButtonEnabled(True)
        self.fy.setObjectName("fy")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fy)
        self.checkBox = QtWidgets.QCheckBox(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setMinimumSize(QtCore.QSize(90, 20))
        self.checkBox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox.setObjectName("checkBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.checkBox)
        self.labelsymmetry = QtWidgets.QLabel(self.centralwidget)
        self.labelsymmetry.setGeometry(QtCore.QRect(180, 257, 48, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelsymmetry.sizePolicy().hasHeightForWidth())
        self.labelsymmetry.setSizePolicy(sizePolicy)
        self.labelsymmetry.setMinimumSize(QtCore.QSize(0, 25))
        self.labelsymmetry.setObjectName("labelsymmetry")
        self.checksym = QtWidgets.QComboBox(self.centralwidget)
        self.checksym.setGeometry(QtCore.QRect(232, 257, 120, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checksym.sizePolicy().hasHeightForWidth())
        self.checksym.setSizePolicy(sizePolicy)
        self.checksym.setMinimumSize(QtCore.QSize(120, 21))
        self.checksym.setMaximumSize(QtCore.QSize(120, 25))
        self.checksym.setObjectName("checksym")
        self.checksym.addItem("")
        self.checksym.addItem("")
        self.radioButtonAs = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonAs.setGeometry(QtCore.QRect(180, 286, 191, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonAs.sizePolicy().hasHeightForWidth())
        self.radioButtonAs.setSizePolicy(sizePolicy)
        self.radioButtonAs.setMinimumSize(QtCore.QSize(0, 20))
        self.radioButtonAs.setMaximumSize(QtCore.QSize(16777215, 20))
        self.radioButtonAs.setAutoExclusive(True)
        self.radioButtonAs.setObjectName("radioButtonAs")
        self.As2 = QtWidgets.QLineEdit(self.centralwidget)
        self.As2.setEnabled(False)
        self.As2.setGeometry(QtCore.QRect(190, 310, 130, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.As2.sizePolicy().hasHeightForWidth())
        self.As2.setSizePolicy(sizePolicy)
        self.As2.setMinimumSize(QtCore.QSize(130, 20))
        self.As2.setMaximumSize(QtCore.QSize(130, 20))
        self.As2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.As2.setDragEnabled(False)
        self.As2.setObjectName("As2")
        self.labelAsmm2_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelAsmm2_2.setGeometry(QtCore.QRect(320, 310, 21, 20))
        self.labelAsmm2_2.setObjectName("labelAsmm2_2")
        self.labeloutput = QtWidgets.QLabel(self.centralwidget)
        self.labeloutput.setGeometry(QtCore.QRect(375, 43, 251, 25))
        self.labeloutput.setMinimumSize(QtCore.QSize(251, 25))
        self.labeloutput.setMaximumSize(QtCore.QSize(251, 25))
        self.labeloutput.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"font: 11pt \"宋体\";")
        self.labeloutput.setObjectName("labeloutput")
        self.textBrowsercalculate = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowsercalculate.setGeometry(QtCore.QRect(375, 144, 251, 318))
        self.textBrowsercalculate.setMinimumSize(QtCore.QSize(251, 318))
        self.textBrowsercalculate.setMaximumSize(QtCore.QSize(251, 318))
        self.textBrowsercalculate.setObjectName("textBrowsercalculate")
        self.labelcalculate = QtWidgets.QLabel(self.centralwidget)
        self.labelcalculate.setGeometry(QtCore.QRect(375, 120, 251, 16))
        self.labelcalculate.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelcalculate.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.labelcalculate.setObjectName("labelcalculate")
        self.labelAs2 = QtWidgets.QLabel(self.centralwidget)
        self.labelAs2.setGeometry(QtCore.QRect(375, 96, 95, 20))
        self.labelAs2.setMinimumSize(QtCore.QSize(95, 20))
        self.labelAs2.setMaximumSize(QtCore.QSize(95, 16777215))
        self.labelAs2.setObjectName("labelAs2")
        self.labelAsmm2 = QtWidgets.QLabel(self.centralwidget)
        self.labelAsmm2.setGeometry(QtCore.QRect(598, 96, 18, 16))
        self.labelAsmm2.setObjectName("labelAsmm2")
        self.labelAs = QtWidgets.QLabel(self.centralwidget)
        self.labelAs.setEnabled(True)
        self.labelAs.setGeometry(QtCore.QRect(375, 72, 95, 20))
        self.labelAs.setMinimumSize(QtCore.QSize(95, 20))
        self.labelAs.setMaximumSize(QtCore.QSize(95, 16777215))
        self.labelAs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelAs.setObjectName("labelAs")
        self.labelA_smm2 = QtWidgets.QLabel(self.centralwidget)
        self.labelA_smm2.setGeometry(QtCore.QRect(598, 72, 18, 16))
        self.labelA_smm2.setObjectName("labelA_smm2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(343, 466, 331, 35))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtoncalculate = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtoncalculate.sizePolicy().hasHeightForWidth())
        self.pushButtoncalculate.setSizePolicy(sizePolicy)
        self.pushButtoncalculate.setMinimumSize(QtCore.QSize(68, 23))
        self.pushButtoncalculate.setMaximumSize(QtCore.QSize(89, 23))
        self.pushButtoncalculate.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButtoncalculate.setObjectName("pushButtoncalculate")
        self.horizontalLayout.addWidget(self.pushButtoncalculate)
        self.pushButtonreturn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonreturn.setObjectName("pushButtonreturn")
        self.horizontalLayout.addWidget(self.pushButtonreturn)
        self.pushButtonclear = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonclear.sizePolicy().hasHeightForWidth())
        self.pushButtonclear.setSizePolicy(sizePolicy)
        self.pushButtonclear.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButtonclear.setObjectName("pushButtonclear")
        self.horizontalLayout.addWidget(self.pushButtonclear)
        self.pushButtonclose = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonclose.sizePolicy().hasHeightForWidth())
        self.pushButtonclose.setSizePolicy(sizePolicy)
        self.pushButtonclose.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButtonclose.setObjectName("pushButtonclose")
        self.horizontalLayout.addWidget(self.pushButtonclose)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 466, 330, 16))
        self.label.setMinimumSize(QtCore.QSize(330, 0))
        self.label.setText("")
        self.label.setObjectName("label")
        self.AAs2 = QtWidgets.QLineEdit(self.centralwidget)
        self.AAs2.setEnabled(False)
        self.AAs2.setGeometry(QtCore.QRect(480, 94, 110, 20))
        self.AAs2.setMinimumSize(QtCore.QSize(0, 20))
        self.AAs2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.AAs2.setObjectName("AAs2")
        self.As = QtWidgets.QLineEdit(self.centralwidget)
        self.As.setEnabled(False)
        self.As.setGeometry(QtCore.QRect(480, 70, 110, 20))
        self.As.setMinimumSize(QtCore.QSize(0, 20))
        self.As.setMaximumSize(QtCore.QSize(16777215, 20))
        self.As.setObjectName("As")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 620, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButtoncalculate.clicked.connect(self.textBrowsercalculate.copy)
        self.pushButtonclear.clicked.connect(self.b.clear)
        self.pushButtonclear.clicked.connect(self.h.clear)
        self.pushButtonclear.clicked.connect(self.l.clear)
        self.pushButtonclear.clicked.connect(self.a_s.clear)
        self.pushButtonclear.clicked.connect(self.N.clear)
        self.pushButtonclear.clicked.connect(self.M1.clear)
        self.pushButtonclear.clicked.connect(self.M2.clear)
        self.pushButtonclear.clicked.connect(self.fc.clear)
        self.pushButtonclear.clicked.connect(self.fy.clear)
        self.pushButtonclose.clicked.connect(MainWindow.close)
        self.pushButtonclear.clicked.connect(self.As2.clear)
        self.radioButtonAs.toggled['bool'].connect(self.As2.setEnabled)
        self.checkBox.toggled['bool'].connect(self.fc.setEnabled)
        self.checkBox.toggled['bool'].connect(self.fy.setEnabled)
        self.checkBox.toggled['bool'].connect(self.ctype.setDisabled)
        self.checkBox.toggled['bool'].connect(self.rtype.setDisabled)
        self.radioButtonAs.toggled['bool'].connect(self.As2.clear)
        self.checkBox.toggled['bool'].connect(self.fc.clear)
        self.checkBox.toggled['bool'].connect(self.fy.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelmain.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">混凝土压弯承载力计算</p></body></html>"))
        self.labelinput.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">输入参数</p></body></html>"))
        self.image.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.lable_b.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">宽度b(mm)</p></body></html>"))
        self.label_h.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">高度h(mm)</p></body></html>"))
        self.label_L.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">长度L(mm)</p></body></html>"))
        self.label_as.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">as=a\'s(mm)</p></body></html>"))
        self.label_N.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">轴力N(kN)</p></body></html>"))
        self.label_M1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">M1(kNm)</p></body></html>"))
        self.label_M2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">M2(kNm)</p></body></html>"))
        self.labelbasenum.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">基本参数</p></body></html>"))
        self.labelconcrete.setText(_translate("MainWindow", "<html><head/><body><p>混凝土级别</p></body></html>"))
        self.labelsteel.setText(_translate("MainWindow", "<html><head/><body><p>纵筋级别</p></body></html>"))
        self.ctype.setItemText(0, _translate("MainWindow", "C15"))
        self.ctype.setItemText(1, _translate("MainWindow", "C20"))
        self.ctype.setItemText(2, _translate("MainWindow", "C25"))
        self.ctype.setItemText(3, _translate("MainWindow", "C30"))
        self.ctype.setItemText(4, _translate("MainWindow", "C35"))
        self.ctype.setItemText(5, _translate("MainWindow", "C40"))
        self.ctype.setItemText(6, _translate("MainWindow", "C45"))
        self.ctype.setItemText(7, _translate("MainWindow", "C50"))
        self.ctype.setItemText(8, _translate("MainWindow", "C55"))
        self.ctype.setItemText(9, _translate("MainWindow", "C60"))
        self.ctype.setItemText(10, _translate("MainWindow", "C65"))
        self.ctype.setItemText(11, _translate("MainWindow", "C70"))
        self.ctype.setItemText(12, _translate("MainWindow", "C75"))
        self.ctype.setItemText(13, _translate("MainWindow", "C80"))
        self.rtype.setItemText(0, _translate("MainWindow", "HPB300"))
        self.rtype.setItemText(1, _translate("MainWindow", "HRBF400"))
        self.rtype.setItemText(2, _translate("MainWindow", "HRB335"))
        self.rtype.setItemText(3, _translate("MainWindow", "HRB400"))
        self.rtype.setItemText(4, _translate("MainWindow", "HRB500"))
        self.rtype.setItemText(5, _translate("MainWindow", "HRBF500"))
        self.labelfc.setText(_translate("MainWindow", "<html><head/><body><p>混凝土fc(MPa)</p></body></html>"))
        self.labelfy.setText(_translate("MainWindow", "<html><head/><body><p>受拉钢筋fy(MPa)</p></body></html>"))
        self.checkBox.setText(_translate("MainWindow", "自定义"))
        self.labelsymmetry.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\">配筋模式</p></body></html>"))
        self.checksym.setItemText(0, _translate("MainWindow", "对称配筋"))
        self.checksym.setItemText(1, _translate("MainWindow", "非对称配筋"))
        self.radioButtonAs.setText(_translate("MainWindow", "已知受压钢筋面积（仅非对称）"))
        self.labelAsmm2_2.setText(_translate("MainWindow", "mm2"))
        self.labeloutput.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">输出结果</p></body></html>"))
        self.labelcalculate.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">计算过程</p></body></html>"))
        self.labelAs2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">受压筋面积</p></body></html>"))
        self.labelAsmm2.setText(_translate("MainWindow", "mm2"))
        self.labelAs.setText(_translate("MainWindow", "<html><head/><body><p>纵向钢筋配筋面积</p></body></html>"))
        self.labelA_smm2.setText(_translate("MainWindow", "mm2"))
        self.pushButtoncalculate.setText(_translate("MainWindow", "计算"))
        self.pushButtonreturn.setText(_translate("MainWindow", "初始化参数"))
        self.pushButtonclear.setText(_translate("MainWindow", "清除输入"))
        self.pushButtonclose.setText(_translate("MainWindow", "关闭程序"))





# 浮点数校验器 [0,99999]， 精度：小数后两位
        doubleValidator = QDoubleValidator()
        doubleValidator.setRange(0, 99999)
        doubleValidator.setNotation(QDoubleValidator.StandardNotation)
        doubleValidator.setDecimals(2)
        
        self.As2.setValidator(doubleValidator)
        self.h.setValidator(doubleValidator)
        self.l.setValidator(doubleValidator)
        self.b.setValidator(doubleValidator)
        self.a_s.setValidator(doubleValidator)
        self.M1.setValidator(doubleValidator)
        self.M2.setValidator(doubleValidator)
        self.N.setValidator(doubleValidator)
    def errorbox(self):
        QMessageBox.warning(self,'标题','警告框消息正文',QMessageBox.Yes|QMessageBox.No,QMessageBox.Yes)
        #QMessageBox.warning(self,"错误提示","请输入正确的参数",QMessageBox.Yes | QMessageBox.No)


    
        
